### ISSUE TITLE
Floating windows

### ISSUE THREAD

**Issue by mesteryui** [NotMugil/dotfiles#24]
I dont' know why I add the rules for do that nmtui and update.sh opens floatly and that doesn't happen

**Comment by NotMugil** [comment]
Yep, I noted that before. The issue is that both nmtui and update.sh opens in kitty and i can't add a rule directly for kitty which would make all terminals to float. The approach I took was to find the title of both windows using 'hyprctl clients' and tried to only add rule for l that But sadly that didn't work. I Need to look into this. Thanks for opening this issue.

**Comment by mesteryui** [comment]
I already solved it, you can do that the windows of kitty will open with a class, the only thing you need to is to set a hyprland rule for the rules of class float:

```bash
kitty -e nmuti --class float_kitty
windowrulev2 = class:^(float_kitty)$
```
